CREATE TABLE `users` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`openid` varchar(255),
	`student_id` varchar(255),
	`teacher_id` varchar(255),
	`role` enum('superadmin','admin','user') DEFAULT 'user',
	`avatar` varchar(255),
	`username` varchar(24) NOT NULL,
	`password` varchar(128) NOT NULL,
	`faculty` varchar(255),
	`major` varchar(255),
	`grade` int,
	`identity` enum('本科生','硕士生','博士生','教职工'),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_student_id_unique` UNIQUE(`student_id`),
	CONSTRAINT `users_username_unique` UNIQUE(`username`),
	CONSTRAINT `username_idx` UNIQUE(`username`)
);
